#!/bin/bash
####  checklist
#wn17,37,08,34,26,11
#wn636, ...
#wn22: cannot reboot

##### MDSTAT
### wn11, wn34, wn636




###################### Fail stat ( total 72 WNs )
### [C6] 634/639:  stuch at init!      --- 21   WNs
### [C7] 30:   no power!               --- 39-2 WNs
### [K4]                               --- 9+5 WNs
##################################
### [C6] to check 620 (no disk!!)
### [C7] to check 37, 22 (D-Bus error), 39


export PDSH_SSH_ARGS_APPEND="-o StrictHostKeyChecking=no"
MACH="se[01-02],disk[01-02],wn[01-37,39-40],proxy"  ## CONDOR WN


C6="wn6[01,11,20-33,35-38,40]"  ### C6 WNs
C7="wn[01-29,31-37,39]"               ### C7 WNs
K4="wk4[18-26]"
AMD="amd[10,12-14]"

MACH="se[01-02],disk[01-02],proxy"  ## South-L04
MACH="${AMD}"
MACH="${C6},${C7},${K4}"



#pdsh -w ${MACH} "uname -a" | sort
#pdsh -w ${MACH} "systemctl enable condor"

#pdsh -w ${MACH} "uname -a"
##pdsh -w ${MACH} "yum -y update"
#pdsh -w ${MACH} "yum -y update --exclude=nordugrid-arc6*; /cvmfs/grid.cern.ch/pakiti/bin/pakiti-client --url https://pakiti.egi.eu/feed/ --site TW-NCHC"

pdsh -w ${MACH} 'yum -y update; /cvmfs/grid.cern.ch/pakiti/bin/pakiti-client --url "https://pakiti.egi.eu/feed/" --site TW-NCHC'


#pdcp -r -w ${MACH} /home/lincy/ca2021 ~/

#pdcp -w ${MACH} /etc/grid-security/vomsdir/cms/voms-cms-auth.app.cern.ch.lsc  /etc/grid-security/vomsdir/cms/


#pdcp -w ${MACH} /install.old/wn_f5/etc/grid-security/grid-mapfile /etc/grid-security/

#pdsh -w ${MACH} "yum install -y psacct; service psacct restart"

#pdsh -w ${MACH} "yum install -y  nordugrid-arc6-plugins-gfal nordugrid-arc6-plugins-xrootd"

#pdsh -w ${MACH} "yum -y update"
#pdsh -w ${MACH} "(cd /; yum -y update ca* )"
#pdsh -w ${MACH} "cat /proc/mdstat"

#pdcp -w ${MACH} /etc/collectd.conf /etc/
#pdsh -w ${MACH} service collectd restart



#pdsh -w ${MACH} "ntpdate 140.110.16.1"
#pdsh -w ${MACH} "uname -a" | sort
#pdsh    -w ${MACH} "(cd /etc/grid-security; mv certificates certificates.OLD; tar zxvf cert.tgz)"


### HEP_OSlibs
#pdsh -w "${MACH}" yum -y install https://linuxsoft.cern.ch/wlcg/centos7/x86_64/wlcg-repo-1.0.0-1.el7.noarch.rpm
#pdsh -w "${MACH}" yum -y install HEP_OSlibs
#pdsh -w "${MACH}" yum -y install lcas lcas-lcmaps-gt4-interface lcas-plugins-basic lcas-plugins-voms lcmaps lcmaps-plugins-basic lcmaps-plugins-voms

### Condor
#pdcp -r -w ${MACH} /install.old/wn_f5/etc/condor /etc/
#pdcp -r -w  ${MACH} /etc/condor/condor_config.local_wn /etc/condor/condor_config.local
#pdsh -w    ${MACH} "rm -rf /var/log/condor/*; service condor restart"
#pdcp -w ${MACH} /etc/condor/config.d/00-htcondor-9.0.config /etc/condor/config.d/
#pdsh -w    ${MACH} "service condor restart"

#pdsh -w    ${MACH} "condor_store_cred -c add -p password; umask 0077; condor_token_create -identity condor@mypool > /etc/condor/tokens.d/condor@mypool; service condor restart"
#pdsh -w    ${MACH} "(yum erase -y condor*; yum install -y https://research.cs.wisc.edu/htcondor/repo/8.8/htcondor-release-current.el7.noarch.rpm; yum install -y condor --disablerepo=UMD-4-updates; service condor restart )"
#pdsh -w    ${MACH}  "yum update -y"


#pdcp -w ${MACH} /etc/hosts /etc/
#pdsh -w ${MACH} service gmond restart



#pdcp -w ${MACH} /install.old/wn_f5/etc/firewalld/services/puppet.xml /etc/firewalld/services/
#pdsh -w ${MACH} service firewalld reload


#pdcp -w ${MACH} /install.old/wn_f5/etc/ganglia/gmond.conf  /etc/ganglia/
#pdsh -w ${MACH} service gmond status


#### CVMFS
#pdsh -w ${MACH} "rm -rf /etc/cvmfs"
#pdcp -r -w ${MACH} /install/wn_c7/etc/cvmfs /etc/
#pdsh -w ${MACH} "cvmfs_config chksetup; service autofs restart"

#### Make grid user
#pdcp -w ${MACH} /install.old/wn_f5/root/make_grid_users  /root/
#pdsh -w ${MACH} "(cd /root; . ./make_grid_users)"

