#!/bin/bash
export PDSH_SSH_ARGS_APPEND="-o StrictHostKeyChecking=no"

MACH="wn[01-10],wn[37-40]"  ## exclude fore
MACH="wn6[01,11,20-40]"
MACH="wk4[18-25]"
MACH="amd11"

#pdsh -w ${MACH} uname -a
pdcp -r -w ${MACH} /install/wn_c7/*  /
pdsh -w ${MACH} "(cd ~/deploy_grid ; . ./make_WN ) "
pdsh -w ${MACH} "(service condor restart; service firewalld restart; cd ~/deploy_grid ; . ./make_grid_users )"
