#!/bin/bash

I0=22
I1=36

for ((i=$I0; i<=$I1; i++)); do
  ipmitool -H 10.0.7.${i} -Uadmin -Padmin chassis bootdev pxe
  sleep 3
  ipmitool -H 10.0.7.${i} -Uadmin -Padmin power reset
done

## Then run 1_makeWN