#!/bin/bash

echo
echo "#### Local 10G"
for i in {01..40}; do
   echo -e "10.200.6.${i#0} \t wn6$i.grid.nchc.org.tw \t wn$i"
done

echo
echo "#### Local 1G"
for i in {01..40}; do
   echo -e "10.0.6.$[${i#0}+100] \t wn$i.eth"
done

echo
echo "#### IPMI"
for i in {01..40}; do
   echo -e "10.3.6.${i#0} \t bmc$i"
done
